services:
    semaphore:
        ports:
            - 4000:3000
        image: semaphoreui/semaphore:v2.17.26
        environment:
            SEMAPHORE_DB_DIALECT: sqlite
            SEMAPHORE_ADMIN: admin
            SEMAPHORE_ADMIN_PASSWORD: semaphoreui#2620#
            SEMAPHORE_ADMIN_NAME: Admin
            SEMAPHORE_ADMIN_EMAIL: admin@localhost
        volumes:
            - semaphore_data:/var/lib/semaphore
            - semaphore_config:/etc/semaphore
            - semaphore_tmp:/tmp/semaphore
volumes:
    semaphore_data:
    semaphore_config:
    semaphore_tmp:

---

